---
- hosts: all
  become: yes
  tasks: 
  - name: install_package
    apt: name=nginx update_cache=yes state=latest
    tags: ["sutup "]
 
  - name: Change NGINX port number
    lineinfile:
      path: /etc/nginx/nginx.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen 8004

  - name: start service
    systemd: name=nginx state=started enable=yes 
