---
- hosts: all
  become: true
  tasks:
    - name: install apache2 package
      apt:
        name: apache2
    - name: updating the package
      copy:
        scr: /home/max2/ansible/playbook/intex.html
        dest: /var/www/html/
        owner: root
        group: root 
        mode: '0644'
    - name: restarting the package   
      systemd:
        name: apache2
        state: started
        enabled: yes
