---
- hosts: all
  become: yes
  tasks: 
   - name: install_package
     package: name=Nginx update_cache=yes state=qlatest
     tags:["sutup "]

   - name: changing port number 
     lineinfile:
       path: /etc/nginx/nginx.conf
       regexp: '^Listen '
       insertafter: '#Listen '
       line: Listen 8004
     notify: changing port

   - name: start service
     service: name=Nginx state=started enable=yes 
