---
- hosts: all
  become: true
  tasks:
    - name: install apache2 package
      apt:
        name: apache2
    - name: updating the package
      copy: 
        dest: /var/www/html/index.html
        content: This is my playbook 
    - name: restarting the package   
      systemd:
        name: apache2
        state: started
        enabled: yes
