---
- name: installing jenkins
- hosts: all
  become: yes
  tasks:
- name: using the and condition
  apt: name=jenkins update_cache=yes state=latest
  when: ansible_distribution="ubuntu" or ansible_distribution_version="22.04"
#This will work only when one condition is false
